baseURL = "https://rahulpnath.com/"
languageCode = "en-us"
title = "Rahul Nath"

# for smart copyright line, leave this blank and check [params.copyright]
copyright = ""

theme = "minimo"

disqusShortname = "rahulpnath"
googleAnalytics = "UA-43172163-1"

enableEmoji = true
enableRobotsTXT = true

pygmentsCodefences = true
pygmentsStyle = "monokailight"

preserveTaxonomyNames = true

Paginate = 20

[params]
ArticlePerPage = 10

[params.info]
description = "Rahul Nath is a programmer, blogger, speaker and enjoys running. Blogs are usually technical or about life in general."

[params.assets]
favicon = "favicon.ico"
customCSS = ["custom.css"]

[params.copyright]
prefix = ""
holder = "Rahul Nath"
startYear = "2009"
suffix = ""

[params.sidebar]
enable = true

[params.widgets]
homepage = ["latest"]
sidebar = ["about","search","sidebar_menu","social_menu"]
footer = []

[taxonomies]
category = "categories"
tag = "tags"

[permalinks]
categories = "/blog/category/:title/"
tags = "/blog/tag/:title/"

# Open Graph
[params.opengraph.twitter]
page = "rahulpnath"

[params.opengraph.facebook]
admins = [774780093] # array of Facebook IDs
appID = ""
pageID = ""

[params.social]
codepen = ""
email = "rahulpnath@gmail.com"
facebook = "rahulpnath"
github = "rahulpnath"
instagram = "rahulpnath"
linkedin = "rahulpnath"
twitter = "rahulpnath"
youtube = "UCBwvQc_3OkejVEZbHjqiNTg"

[menu]
	[[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog"
    weight = 1